name: advanced_build

on: [push, pull_request]

jobs:
  build_linux_omp:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Download Conan package manager.
        run: |
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           conan --version

      - name: configure
        run: >
          mkdir build && cd build && cmake ..
          -DCS_BUILD_WARNINGS_AS_ERRORS=ON
          -DCS_USE_OPENMP=ON

      - name: build
        run: cmake --build build --config Debug

      - name: unit-tests
        run: cd build && ctest


  build_linux_static_omp:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Download Conan package manager.
        run: |
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           conan --version

      - name: configure
        run: >
          mkdir build && cd build && cmake ..
          -DCS_BUILD_WARNINGS_AS_ERRORS=ON
          -DBUILD_SHARED_LIBS=OFF
          -DCS_USE_OPENMP=ON

      - name: build
        run: cmake --build build --config Debug

      - name: unit-tests
        run: cd build && ctest



  build_windows_openmp:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Download Conan package manager.
        run: |
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           conan --version

      - name: configure
        run: >
          mkdir build && cd build && cmake ..
          -DCS_BUILD_WARNINGS_AS_ERRORS=ON
          -DCS_USE_OPENMP=ON

      - name: build
        run: cmake --build build --config Debug
      - name: test
        run: cd build && ctest -C Debug


  build_windows_openmp_static:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Download Conan package manager.
        run: |
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           conan --version

      - name: configure
        run: >
          mkdir build && cd build && cmake ..
          -DCS_BUILD_WARNINGS_AS_ERRORS=ON
          -DBUILD_SHARED_LIBS=OFF
          -DCS_USE_OPENMP=ON

      - name: build
        run: cmake --build build --config Debug
      - name: test
        run: cd build && ctest -C Debug