name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get build wrapper
        run: |
          cd /tmp
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          /tmp/build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make clean all

      - name: unit-tests
        run: |
          cd build
          ctest

      - name: Upload build wrapper result
        uses: actions/upload-artifact@v2
        with:
          name: build_wrapper_output_directory
          path: build/build_wrapper_output_directory

  gcov:
    uns-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #- name: Set up Python 3.8
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: 3.8

    - name: Install gcov
      run: |
        apt-get update
        pip3 install gcovr
        gcovr --version

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Download build wrapper result
        uses: actions/download-artifact@v2
        with:
          name: build_wrapper_output_directory
          path: build/build_wrapper_output_directory

      - name: get sonar scanner
        run: |
          cd /tmp
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
          unzip sonar-scanner-cli-4.5.0.2216-linux.zip

      - name: run sonar scanner
        run: |
          /tmp/sonar-scanner-4.5.0.2216-linux/bin/sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

