name: build

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: unit-tests
        run: |
          cd build
          ctest

  build_macos:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: unit-tests
        run: |
          cd build
          ctest
