name: build

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get specific version CMake, v3.19.2
        uses: lukka/get-cmake@v3.19.2

      - name: Download Conan package manager.
        run: |
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           conan --version

      - name: configure
        run: cmake --version && mkdir build && cd build && cmake .. -DCS_BUILD_WARNINGS_AS_ERRORS=ON

      - name: build
        run: cmake --build build --config Debug

      - name: unit-tests
        run: cd build && ctest

  build_macos:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2

      - name: Download Conan package manager.
        run: |
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           conan --version

      - name: configure
        run: cmake --version && mkdir build && cd build && cmake .. -DCS_BUILD_WARNINGS_AS_ERRORS=ON

      - name: build
        run: cmake --build build --config Debug

      - name: unit-tests
        run: cd build && ctest

  build_windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Download Conan package manager.
        run: |
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           conan --version

      - name: configure
        run: cmake --version && mkdir build && cd build && cmake .. -DCS_BUILD_WARNINGS_AS_ERRORS=ON
      - name: build
        run: cmake --build build --config Debug
      - name: test
        run: cd build && ctest -C Debug
